### ISSUE TITLE
Use custom at-rules

### ISSUE THREAD

**Issue by ai** [jo-asakura/postcss-neat#1]
Libraries with mixins is a Sass way. There is no reason to use `postcss-mixin` in plugins like `postcss-neat`. You should add custom properties:

```css
.element {
  neat-span-columns 6;
}
```

**Comment by ai** [comment]
@jo-asakura check out [postcss-flexgrid](https://www.npmjs.com/package/postcss-flexgrid)

**Comment by jo-asakura** [comment]
@ai Yep, I'm planning on adding that as an alternative way of using `postcss-neat`.

**Comment by ai** [comment]
@jo-asakura why not the main way? :)

**Comment by jo-asakura** [comment]
@ai To give people a choice especially for those who is coming from Sass world. Also, having `@mixing` in front of your rule makes it's more searchable and readable in a codebase.

**Comment by ai** [comment]
PostCSS is not a Sass ;-). We should help new users, but not by moving bad solutions from Sass.

`neat-` property prefix will make searching and reading even better ;-).

**Comment by jo-asakura** [comment]
Agree, that should do it.

**Comment by jedmao** [comment]
@jo-asakura you said you want to give people a choice, but isn't [choice an anti-pattern](https://twitter.com/everzet/status/444045856900407296)?
