### ISSUE TITLE
Official browser support

### ISSUE THREAD

**Issue by qasimalyas** [jo-asakura/postcss-neat#14]
Hi,

Is there an official list of browsers ```neat``` is able to work on? I ask because I think some of the generated code can optimised to produce a better output. Namely the ```zoom: 1``` for clear fix is only applicable to ie6 and 7. Is that really needed if that browser isn't supported? 

Could be quite a bit of savings in file size for bigger projects.

**Comment by jo-asakura** [comment]
I believe it's the same browser support what Bourbon Neat provides (or it was at the time of porting it over). If you want to clean up compiled CSS you could probably use 3rd party plugins to do that.
