### ISSUE TITLE
Nest @media is not working

### ISSUE THREAD

**Issue by simoaklan** [jo-asakura/postcss-neat#19]
I tried to apply the code you have mentioned in your explanation

       .col-6 {
  				
  				@neat-span-columns 6;
  				@neat-omega;
  				@media screen and (width < 768px)
  				{
  					@neat-span-columns 12;
  				}
  				
  				
 			}

but, I got code like this which is not applied in my browser.

    .col-6 {
  				@media screen and (max-width: 767.999px)
  				{
  					display: block;
  					float: left;
  					margin-right: 2.35765160%;
  					width: 100.00000000%;
  					&:last-child {
      margin-right: 0;

    }
  				}
  				display: block;
  				float: left;
  				margin-right: 2.35765160%;
  				width: 48.82117420%;
  				margin-right: 0
  				
  				
 			}

Am I doing it the right way? I tried to put postcss-media-minmax before and after postcss-neat and I got the same result

my Gulp file 

    var gulp = require('gulp');
    gulp.task('css', function () {
    var processors = [
      
      require('autoprefixer')({ browsers: ['last 1 version'] }),
      require('postcss-media-minmax'),
      require('postcss-neat')(/* { options } */)
      
      
    ];
    return gulp.src('./src/grid.css')
      .pipe(require('gulp-postcss')(processors))
      .pipe(gulp.dest('./dest/'));
      })
      .task('default', ['styles']);

**Comment by npofopr** [comment]
Worked for me https://github.com/npofopr/postcss-neat-test/blob/master/gulpfile.js
and css https://github.com/npofopr/postcss-neat-test/blob/master/src/css/style.css

**Comment by jo-asakura** [comment]
@simoaklan sorry for the super late response but in order to use `@media` queries you will have to include `postcss-media-minmax` in your build like it's stated in readme:
> To make your layout responsive, use the postcss-media-minmax media queries functionality...

A simple example would be:
```
gulp.task('css', function () {
  var concat = require('gulp-concat');
  var postcss = require('gulp-postcss');
  var postcssNeat = require('postcss-neat');
  var postcssNested = require('postcss-nested');
  var postcssVars = require('postcss-simple-vars');
  var postcssMinMax = require('postcss-media-minmax');
  var autoprefixer = require('autoprefixer-core');

  var processors = [
    autoprefixer({ browsers: ['last 1 version'] }),
    postcssNeat({}),
    postcssNested,
    postcssVars,
    postcssMinMax
  ];

  return gulp.src('./demo/input.scss')
    .pipe(postcss(processors))
    .pipe(concat('output.css'))
    .pipe(gulp.dest('./demo/'));
});
```
