### ISSUE TITLE
How to define neatGutterWidth in PX ?

### ISSUE THREAD

**Issue by ethyde** [jo-asakura/postcss-neat#23]
Hi,

`neatMaxWidth : "1170px"` work, but `neatGutterWidth: "30px"` not, and result of NaN.

Thx.

**Comment by jo-asakura** [comment]
@ethyde, it won't break anymore but it will not honor `neatGutterWidth` pixel value.. it uses unitless values because the final gutter is percentage based value.

**Comment by qasimalyas** [comment]
Can the new version 2.5.3 be pushed to NPM please?

**Comment by jo-asakura** [comment]
@qasimalyas, sorry, I didn't notice it wasn't published. It's now.
