### ISSUE TITLE
Grid configuration

### ISSUE THREAD

**Issue by jedmao** [jo-asakura/postcss-neat#6]
Any way to configure the following?
- Number of grid columns
- Column width
- Grid margin

**Comment by qasimalyas** [comment]
Also worth confirming if the outer gutter can be specified as well changing the grid configuration on a breakpoint level.

Is there any further documentation as to what else can be defined apart from outer-container and span-columns

**Comment by jedmao** [comment]
Basically, any properties that you can find in [online](http://www.responsivegridsystem.com/calculator/) [grid](http://www.pagecolumn.com/grid_layout_generator.htm) [generators](http://gridinator.com/) should be configurable here too.

**Comment by jo-asakura** [comment]
@jedmao, there are several things you can configure and they can be found here [https://github.com/jo-asakura/postcss-neat/blob/master/lib/core/variables.es6.js](https://github.com/jo-asakura/postcss-neat/blob/master/lib/core/variables.es6.js) (compiled version).

**Comment by jedmao** [comment]
Can you add some docs on the readme for this?

**Comment by admdh** [comment]
+1

**Comment by qasimalyas** [comment]
This definitely needs more documentation. It's unclear as to how some variables can be used in a mixin. Which mixin?

**Comment by jo-asakura** [comment]
@qasimalyas, @jedmao, https://github.com/jo-asakura/postcss-neat#custom-settings

**Comment by jedmao** [comment]
Thanks!
