### ISSUE TITLE
Updating NPM version of post-neat

### ISSUE THREAD

**Issue by qasimalyas** [jo-asakura/postcss-neat#7]
Hi,

Is there a timeframe of when postcss-neat will be updated on NPM to resolve https://github.com/jo-asakura/postcss-neat/issues/4.

The current version is 1.1.0 whereas on NPM its v 1.0.1.

**Comment by okiii** [comment]
+1

**Comment by jo-asakura** [comment]
@qasimalyas & @okiii, done. Sorry, guys, absolutely forgot about npm update :disappointed:

**Comment by qasimalyas** [comment]
Sweet. Let's get gridding!
