### ISSUE TITLE
Option to create background grid

### ISSUE THREAD

**Issue by qasimalyas** [jo-asakura/postcss-neat#9]
It would be really helpful to have a grid applied as a background to the container. At the moment its a bit difficult to see if columns / gutters are aligned correctly. I know susy does this very well so i know that this should be possible.

**Comment by jo-asakura** [comment]
@qasimalyas, could attach an example or screen shot of what you want to see.

**Comment by qasimalyas** [comment]
@jo-asakura So susy has the ability to add a background grid - there's a [post about it here](http://www.zell-weekeat.com/susy-grid-background-image/).  An example of grids (from the link) can be [seen here](http://codepen.io/zellwk/pen/jDFdI).

So instead of create a [background graphic and adding that to the container](http://jo-asakura.github.io/postcss-neat/demo.html) would it possible to a debug option which creates a CSS gradient background. See the [susy grid example](http://codepen.io/zellwk/pen/jDFdI)

**Comment by jo-asakura** [comment]
@qasimalyas, Got it.. will add that shortly. Also, `debug` option will go to `postcss-neat`'s settings that you use to init the plugin.

**Comment by jo-asakura** [comment]
Implemented https://github.com/jo-asakura/postcss-neat/pull/13

**Comment by jo-asakura** [comment]
There is no need for `debug` flag as I wanted initially. The usage is:
```css
.container {
  @neat-outer-container;
  @neat-show-grid; /* defaults to 1 12 */
}
```

^-- also added to the README.
